// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnyzkivuqsrspwhihuwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFueXpraXZ1cXNyc3B3aGlodXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzgwMjUsImV4cCI6MjA2MzI1NDAyNX0.xCk3k33Jwn9BZlZqwV5Ur50mXjbtu0D308m9JaYig5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);